# Generated by Django 3.0.8 on 2020-08-12 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0006_auto_20200811_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='voter',
            field=models.ManyToManyField(null=True, related_name='voter_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='voter',
            field=models.ManyToManyField(null=True, related_name='voter_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
